tf:
  frozenModelPath: inception-v3/retrained_graph.pb
  labelsPath: inception-v3/retrained_labels.txt
  outputLayer: InceptionV3/Predictions/Reshape_1
  image:
    width: 299
    height: 299
    mean: 0
    scale: 255

spring.http.multipart.max-file-size: 5MB